

defaults:
  - scope:
      path: "/pages/excel/"
      type: "excel"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "documentation"
    values:
      layout: "products"
  - scope:
      path: ""
    values:
      layout: "default"

# this property is useful for conditional filtering of content that is separate from the PDF.
output: web 

sidebars:
- product1_sidebar

markdown: kramdown

github_editme_path: DavidmSalm/DavidmSalm.github.io/tree/main/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

